version: 0.2
ignorePaths: ["elections/**/*"]
words:
    - adot
    - apac
    - cdevents
    - cicd
    - cncf
    - codecov
    - codeowners
    - DASD
    - dynatrace
    - easycla
    - eiffel
    - emea
    - faas
    - gitter
    - Hostmetrics
    - jemmic
    - keptn
    - kubecon
    - liatrio
    - lightstep
    - logz
    - maintainership
    - observiq
    - opentelemetry
    - opentelemetrybot
    - otel
    - otep
    - otlp
    - passcodes
    - proto
    - pytest
    - REXX
    - runtimes
    - signup
    - skyscanner
    - splk
    - subdir
    - subproject
    - subprojects
    - subrepository
    - supermajority
    - Sysplex
    - tekton
    - tiebreaking
    - timebox
    - timeboxing
    - timeslot
    - tocstop
    - trendable
    - triager
    - triagers
    # names and github handles
    - acramsay
    - adrielp
    - afrittoli
    - alolita
    - amye
    - aniszczyk
    - arbiv
    - armin
    - arminru
    - austinlparker
    - beedgen
    - blanco
    - bogdan
    - bogdandrutu
    - boten
    - breedx
    - caramanolis
    - carlosalberto
    - cartermp
    - cijo
    - codeboten
    - danielgblanco
    - darren17082
    - davdai
    - denisivan
    - dennisme
    - dnsmichi
    - drutu
    - dsotirakis
    - dyla
    - dyladan
    - elfo404
    - ericchapman80
    - e-backmark-ericsson
    - fong
    - henrikrexed
    - horovits
    - jackjia
    - jaglowski
    - jigar
    - jimporell
    - jpkrohling
    - jsuereth
    - juraci
    - kamphaus
    - kanzhelev
    - kröhling
    - krzko
    - kuisathaverat
    - lalitb
    - lmolkova
    - lucavallin
    - magnusbaeck
    - mancuso
    - martinkuba
    - mateuszrzeszutek
    - mayur
    - mayurkale
    - mhausenblas
    - mirabella
    - msomasu
    - mtwo
    - mwear
    - najaryan
    - nakamura
    - Nale
    - neumann
    - neumüller
    - novotny
    - ocelotl
    - oleg-nenashev
    - paixão
    - parsana
    - patrickhousley
    - pmpaulino
    - poncelow
    - reiley
    - reyang
    - rrschulze
    - ruech
    - rynn
    - salnikov
    - scavarda
    - scheler
    - sergey
    - severin
    - sguyon
    - sharma
    - sharrmander
    - shkuro
    - sigelman
    - srikanthccv
    - stalnaker
    - suereth
    - sureth
    - svrnm
    - tarnovski
    - tedsuo
    - thisthat
    - tigran
    - tigrannajaryan
    - trask
    - tsloughter
    - tylerbenson
    - xibz
    - xoscar
    - yahn
    - youngaaronm
    # slack spaces
    - otel-agentmanwg
    - otel-comms
    - otel-ebpf
