version: 0.2
ignorePaths: ["elections/**/*"]
words:
    - apac
    - cicd
    - cncf
    - codecov
    - codeowners
    - dynatrace
    - easycla
    - emea
    - faas
    - gitter
    - keptn
    - kubecon
    - lightstep
    - maintainership
    - observiq
    - opentelemetry
    - opentelemetrybot
    - otel
    - otep
    - otlp
    - passcodes
    - proto
    - runtimes
    - signup
    - skyscanner
    - splk
    - subdir
    - subproject
    - subprojects
    - subrepository
    - supermajority
    - tiebreaking
    - timebox
    - timeboxing
    - timeslot
    - tocstop
    - trendable
    - triager
    - triagers
    # names and github handles
    - adrielp
    - alolita
    - amye
    - aniszczyk
    - arbiv
    - armin
    - arminru
    - austinlparker
    - beedgen
    - blanco
    - bogdan
    - bogdandrutu
    - boten
    - breedx
    - caramanolis
    - carlosalberto
    - cartermp
    - cijo
    - codeboten
    - danielgblanco
    - denisivan
    - dennisme
    - drutu
    - dyla
    - dyladan
    - fong
    - henrikrexed
    - horovits
    - jaglowski
    - jigar
    - jpkrohling
    - jsuereth
    - juraci
    - kanzhelev
    - kröhling
    - lalitb
    - lmolkova
    - mancuso
    - martinkuba
    - mateuszrzeszutek
    - mayur
    - mayurkale
    - mirabella
    - mtwo
    - mwear
    - najaryan
    - nakamura
    - neumann
    - neumüller
    - novotny
    - ocelotl
    - paixão
    - parsana
    - patrickhousley
    - poncelow
    - reiley
    - reyang
    - ruech
    - rynn
    - salnikov
    - scavarda
    - scheler
    - sergey
    - severin
    - sharma
    - sharrmander
    - shkuro
    - sigelman
    - srikanthccv
    - stalnaker
    - suereth
    - sureth
    - svrnm
    - tarnovski
    - tedsuo
    - thisthat
    - tigran
    - tigrannajaryan
    - trask
    - tsloughter
    - tylerbenson
    - xoscar
    - yahn
    # slack spaces
    - otel-agentmanwg
    - otel-comms
    - otel-ebpf
