version: 0.2
ignorePaths: ["elections/**/*"]
# Ignore certain patterns in the sigs.yml file
patterns:
    - name: Slack Channel ID
      pattern: "id: [A-Z0-9]{11}"
    - name: Google Docs ID
      pattern: "value: [a-zA-Z0-9-_]+"
ignoreRegExpList:
    - Slack Channel ID
    - Google Docs ID
words:
    - DASD
    - datadog
    - dynatrace
    - easycla
    - eiffel
    - elastic
    - emea
    - faas
    - galkleinman
    - gitter
    - grafana
    - gyliu513
    - Hostmetrics
    - isovalent
    - labs
    - Liudmila
    - Nale
    - REXX
    - Sysplex
    - acramsay
    - adot
    - adrielp
    - afrittoli
    - alanwest
    - alevenberg
    - alolita
    - amye
    - aniszczyk
    - apac
    - anoshin
    - arbiv
    - armin
    - arminru
    - austinlparker
    - beedgen
    - blanco
    - bogdan
    - bogdandrutu
    - boten
    - breedx
    - calendar-agent-mgmt
    - calendar-ebpf
    - caramanolis
    - carlosalberto
    - cartermp
    - cdevents
    - cicd
    - cijo
    - cncf
    - codeboten
    - codecov
    - codeowners
    - danielgblanco
    - darren17082
    - davdai
    - denisivan
    - dennisme
    - dmitrii
    - dpauls
    - dnsmichi
    - dpauls
    - drewby
    - drutu
    - dsotirakis
    - dyla
    - dyladan
    - dynatrace
    - e-backmark-ericsson
    - easycla
    - eiffel
    - elfo404
    - emea
    - endsigs
    - ericchapman80
    - faas
    - fong
    - gitter
    - henrikrexed
    - hongalex
    - horovits
    - jackjia
    - jaglowski
    - jcocchi
    - jemmic
    - jigar
    - jimporell
    - jmacd
    - joaopgrassi
    - jpkrohling
    - jsuereth
    - juraci
    - kamphaus
    - kanzhelev
    - kelnage
    - keptn
    - krzko
    - kröhling
    - kubecon
    - kuisathaverat
    - lalitb
    - lambdanis
    - liatrio
    - lightstep
    - lmolkova
    - logz
    - lucavallin
    - magnusbaeck
    - maintainership
    - mancuso
    - martinkuba
    - mateuszrzeszutek
    - mayur
    - mayurkale
    - mdelfabro
    - mhausenblas
    - mirabella
    - mjwolf
    - molkova
    - msomasu
    - mtwo
    - mwear
    - najaryan
    - nakamura
    - neumann
    - neumüller
    - nirga
    - novotny
    - observiq
    - ocelotl
    - oleg-nenashev
    - opentelemetry
    - opentelemetrybot
    - otel
    - otel-agentmanwg
    - otel-comms
    - otel-ebpf
    - otep
    - otlp
    - paixão
    - parsana
    - passcodes
    - patrickhousley
    - pmpaulino
    - poncelow
    - proto
    - pyohannes
    - pytest
    - raesene
    - reiley
    - reyang
    - rrschulze
    - ruech
    - runtimes
    - rynn
    - salnikov
    - scavarda
    - scheler
    - semconv
    - sergey
    - severin
    - sguyon
    - sharma
    - sharrmander
    - shkuro
    - sigelman
    - signup
    - skyscanner
    - sourabh1007
    - splk
    - srikanthccv
    - stalnaker
    - subdir
    - subproject
    - subprojects
    - subrepository
    - sudivate
    - suereth
    - supermajority
    - svrnm
    - tarnovski
    - tedsuo
    - tekton
    - thisthat
    - tiebreaking
    - tigran
    - tigrannajaryan
    - timebox
    - timeboxing
    - timeslot
    - tocstop
    - trask
    - trendable
    - triager
    - triagers
    - trisch-me
    - tsloughter
    - tylerbenson
    - xibz
    - xoscar
    - yahn
    - youngaaronm
