version: 0.2
ignorePaths:
  ["elections/**/*", "tools/github/*", "scripts/**/*.py", "scripts/**/*.sh"]
# Ignore certain patterns in the sigs.yml file
patterns:
  - name: Slack Channel ID
    pattern: "id: [A-Z0-9]{11}"
  - name: Google Docs ID
    pattern: "value: [a-zA-Z0-9-_]+"
  - name: "GitHub Handle"
    pattern: "@[a-zA-Z0-9-_]+\\b"
  - name: "GitHub Handle in YML"
    pattern: "github: [a-zA-Z0-9-_]+"
ignoreRegExpList:
  - Slack Channel ID
  - Google Docs ID
  - GitHub Handle
  - GitHub Handle in YML
words:
    - Alff
    - Arize
    - Ashpole
    - Baeyens
    - Collibra
    - Coralogix
    - DASD
    - Docu
    - Dosu
    - datadog
    - devex
    - devstats
    - dynatrace
    - easycla
    - eiffel
    - elastic
    - emea
    - faas
    - gitter
    - grafana
    - Hostmetrics
    - hostmetricsreceiver
    - Instrgen
    - jemmic
    - keptn
    - kubecon
    - k8sclusterreceiver
    - Langfuse
    - Langtrace
    - liatrio
    - lightstep
    - logz
    - maintainership
    - observiq
    - opentelemetry
    - opentelemetrybot
    - otel
    - otep
    - otlp
    - passcodes
    - proto
    - pytest
    - isovalent
    - labs
    - Liudmila
    - Nale
    - REXX
    - scaphandre
    - Sysplex
    - acramsay
    - adot
    - agentmanwg
    - alolita
    - amye
    - andré
    - aniszczyk
    - apac
    - anoshin
    - armin
    - beedgen
    - beemer
    - bertysentry
    - blanco
    - bogdan
    - boten
    - calendar-agent-mgmt
    - calendar-ebpf
    - caramanolis
    - cdevents
    - chrs
    - cicd
    - cijo
    - cncf
    - codeboten
    - codecentric
    - codecov
    - codeowners
    - comms
    - credly
    - danielgblanco
    - darren17082
    - davdai
    - denisivan
    - dennisme
    - dineshg
    - dmitrii
    - dmitryax
    - dpauls
    - dnsmichi
    - dpauls
    - drewby
    - drutu
    - dyla
    - dynatrace
    - easycla
    - ebpf
    - eiffel
    - emea
    - endsigs
    - faas
    - fong
    - frzifus
    - gbbr
    - genai
    - gitter
    - gitdm
    - henrikrexed
    - heptio
    - hongalex
    - horovits
    - instrgen
    - jackjia
    - jaglowski
    - javaagent
    - jemmic
    - juraci
    - kaiyan-sheng
    - kamphaus
    - kanzhelev
    - kelnage
    - keptn
    - krzko
    - kröhling
    - kubecon
    - kuisathaverat
    - lalitb
    - lambdanis
    - lexis
    - liatrio
    - lightstep
    - logz
    - lucavallin
    - lukas
    - lycheeverse
    - magnusbaeck
    - maintainership
    - mancuso
    - marceloamaral
    - martinkuba
    - mateuszrzeszutek
    - mayur
    - mayurkale
    - Metry
    - mdelfabro
    - mhausenblas
    - mirabella
    - mjwolf
    - mkorbi
    - molkova
    - msomasu
    - MSYS
    - PATHCONV
    - mtwo
    - mwear
    - najaryan
    - nakamura
    - neumann
    - neumüller
    - nexis
    - nirga
    - nikimanoledaki
    - novotny
    - observiq
    - Olly
    - opamp
    - OpenLIT
    - opentelemetry
    - opentelemetrybot
    - ossf
    - otel
    - otel-agentmanwg
    - otel-comms
    - otel-ebpf
    - otelbot
    - otep
    - otlp
    - OTAP
    - OTTL
    - outreachy
    - Packagist
    - Prometheus
    - paixão
    - pająk
    - passcodes
    - poncelow
    - proto
    - protos
    - pytest
    - Quesma
    - raesene
    - reiley
    - rolldice
    - ruech
    - runtimes
    - rynn
    - rossf7
    - salnikov
    - sallyom
    - sarif
    - scavarda
    - semconv
    - sergey
    - severin
    - sguyon
    - sharma
    - shkuro
    - sigelman
    - signup
    - skyscanner
    - sloughter
    - snyk
    - splk
    - stalnaker
    - subdir
    - subproject
    - subprojects
    - subrepository
    - sudivate
    - suereth
    - supermajority
    - Traceloop
    - tarnovski
    - tekton
    - thisthat
    - tiebreaking
    - tigran
    - timebox
    - timeboxing
    - timeslot
    - tocstop
    - trask
    - trendable
    - triager
    - triagers
    - teamcity
    - uninstrumented
    - vtex
    - yahn
