version: 0.2
ignorePaths:
  [
    "elections/**/*",
    "tools/github/*",
    "scripts/**/*.py",
    "scripts/**/*.sh",
    "workstreams.yml",
    "people.yml",
  ]
# Ignore certain patterns in the workstreams.yml file
patterns:
  - name: Slack Channel ID
    pattern: "\\bC[A-Z0-9]{10}\\b"
  - name: Google Docs ID
    pattern: "value: [a-zA-Z0-9-_]+"
  - name: "GitHub Handle"
    pattern: "@[a-zA-Z0-9-_]+\\b"
  - name: "GitHub Handle in YML"
    pattern: "github: [a-zA-Z0-9-_]+"
ignoreRegExpList:
  - Slack Channel ID
  - Google Docs ID
  - GitHub Handle
  - GitHub Handle in YML
words:
  - Abdallah
  - Abinet
  - Adell
  - Adriel
  - Alain
  - Alff
  - Arize
  - Aronoff
  - Ashpole
  - Baeyens
  - Blancas
  - Bratz
  - Braydon
  - Bronto
  - Bushe
  - Causely
  - Cheler
  - Ciukaj
  - Collibra
  - Coralogix
  - Cortez
  - Cowart
  - César
  - DASD
  - Debele
  - Develocity
  - Docu
  - Dogan
  - Dosu
  - Dubbo
  - Díaz
  - EPEL
  - Ello
  - Fordyce
  - Francesco
  - Furst
  - Harshit
  - Hasain
  - Hendrik
  - Hostmetrics
  - Hrabusa
  - Instrgen
  - Jaana
  - Jhin
  - Joaquín
  - Joshi
  - Juraj
  - Kains
  - Kamel
  - Kanal
  - Karlie
  - Kemal
  - Kielty
  - Kuba
  - Kushwaha
  - LFPCC
  - Langfuse
  - Langtrace
  - Liudmila
  - Luca
  - Lukasz
  - MSYS
  - Magnusson
  - Makefiles
  - Marylia
  - Mathieu
  - Matthieu
  - Metry
  - Michálek
  - Morgado
  - Muñoz
  - NUMA
  - Nale
  - Noirbusson
  - OCPUs
  - OTAP
  - OTTL
  - Ognibene
  - Olly
  - OpenLIT
  - PATHCONV
  - PECL
  - Packagist
  - Pham
  - Phoonix
  - Pichler
  - Prometheus
  - Purvi
  - Quesma
  - REXX
  - Rexed
  - Rohit
  - Rosman
  - Santosh
  - Schmitt
  - Sysplex
  - Tamir
  - Tero
  - Thiru
  - Tigerbeetle
  - Traceloop
  - VNIC
  - Vasconcellos
  - Villela
  - Vitor
  - Workiva
  - Yusuf
  - acramsay
  - adot
  - adrielp
  - agentic
  - agentmanwg
  - alolita
  - amye
  - andré
  - aniszczyk
  - anoshin
  - apac
  - armin
  - austinlparker
  - automations
  - beedgen
  - beemer
  - behaviour
  - behaviours
  - bertysentry
  - blanco
  - bogdan
  - boten
  - calendar-agent-mgmt
  - calendar-ebpf
  - calendar-localization-ptbr
  - caramanolis
  - cdevents
  - chrs
  - cicd
  - cijo
  - cijothomas
  - cncf
  - codeboten
  - codecentric
  - codecov
  - codeowners
  - comms
  - credly
  - danielgblanco
  - darren17082
  - dartastic
  - dartdoc
  - datadog
  - davdai
  - denisivan
  - dennisme
  - devex
  - devrel
  - devstats
  - dineshg
  - distro
  - distros
  - dmitrii
  - dmitryax
  - dnsmichi
  - dpauls
  - drewby
  - drutu
  - dyla
  - dynatrace
  - easycla
  - ebpf
  - eiffel
  - elastic
  - emea
  - endgc
  - endsigs
  - endtc
  - exporterhelper
  - faas
  - fong
  - frzifus
  - gatekeeping
  - gbbr
  - genai
  - gitdm
  - gitter
  - govanityurls
  - grafana
  - growpart
  - henrikrexed
  - heptio
  - hongalex
  - horovits
  - hostmetricsreceiver
  - iflag
  - instrgen
  - ipfix
  - isovalent
  - jackjia
  - jaglowski
  - javaagent
  - jemmic
  - juraci
  - k8sclusterreceiver
  - kaiyan-sheng
  - kamphaus
  - kanzhelev
  - kelnage
  - keptn
  - krzko
  - kröhling
  - kubecon
  - kuisathaverat
  - labs
  - lalitb
  - lambdanis
  - lexis
  - liatrio
  - lightstep
  - logz
  - lucavallin
  - lukas
  - lycheeverse
  - magnusbaeck
  - maintainership
  - mancuso
  - marceloamaral
  - martinkuba
  - mateuszrzeszutek
  - mayur
  - mayurkale
  - mdelfabro
  - mhausenblas
  - mirabella
  - mjwolf
  - mkorbi
  - molkova
  - mottibec
  - msomasu
  - mtwo
  - mwear
  - najaryan
  - nakamura
  - netflow
  - netflowreceiver
  - neumann
  - neumüller
  - nexis
  - nikimanoledaki
  - nirga
  - novotny
  - npmjs
  - observiq
  - ocgroups
  - opamp
  - opentelemetry
  - opentelemetrybot
  - oracleoci
  - oraclevda
  - ospf
  - ossf
  - otel
  - otel-agentmanwg
  - otel-comms
  - otel-ebpf
  - otel-localization-ptbr
  - otel-localization-zhcn
  - otelbot
  - otelcol
  - otep
  - otlp
  - outreachy
  - paixão
  - pająk
  - passcodes
  - pavolloffay
  - pessers
  - poncelow
  - proto
  - protos
  - pytest
  - raesene
  - readmemd
  - reiley
  - rescan
  - roadmaps
  - rolldice
  - rollup
  - rossf7
  - ruech
  - runtimes
  - rynn
  - sallyom
  - salnikov
  - sarif
  - scaphandre
  - scavarda
  - schäfer
  - semconv
  - sergey
  - serkan
  - severin
  - sguyon
  - sharma
  - shiftyp
  - shkuro
  - sig-localization-ptbr
  - sig-localization-zhcn
  - sigelman
  - signup
  - skyscanner
  - sloughter
  - snmp
  - snmpreceiver
  - snmptrapreceiver
  - snyk
  - splk
  - stalnaker
  - subdir
  - subproject
  - subprojects
  - subrepository
  - sudivate
  - suereth
  - supermajority
  - tarnovski
  - teamcity
  - tekton
  - telco
  - thisthat
  - tiebreaking
  - tigran
  - timebox
  - timeboxing
  - timeslot
  - traceroute
  - trask
  - trendable
  - triager
  - triagers
  - uninstrumented
  - unstaffed
  - usermod
  - vanityurls
  - vtex
  - warre
  - workstream
  - workstreams
  - yahn
  - zizmor
  - özal
