version: 0.2
ignorePaths:
  ["elections/**/*", "tools/github/*", "scripts/**/*.py", "scripts/**/*.sh"]
# Ignore certain patterns in the sigs.yml file
patterns:
  - name: Slack Channel ID
    pattern: "id: [A-Z0-9]{11}"
  - name: Google Docs ID
    pattern: "value: [a-zA-Z0-9-_]+"
  - name: "GitHub Handle"
    pattern: "@[a-zA-Z0-9-_]+\\b"
  - name: "GitHub Handle in YML"
    pattern: "github: [a-zA-Z0-9-_]+"
ignoreRegExpList:
  - Slack Channel ID
  - Google Docs ID
  - GitHub Handle
  - GitHub Handle in YML
words:
  - Abinet
  - Alff
  - Arize
  - Ashpole
  - automations
  - Baeyens
  - calendar-localization-ptbr
  - Causely
  - Cheler
  - Collibra
  - Coralogix
  - Cortez
  - DASD
  - Debele
  - Díaz
  - Docu
  - Dosu
  - Dubbo
  - datadog
  - Develocity
  - devex
  - devstats
  - dynatrace
  - easycla
  - eiffel
  - elastic
  - emea
  - faas
  - gitter
  - grafana
  - Hostmetrics
  - hostmetricsreceiver
  - Instrgen
  - jemmic
  - Joaquín
  - Kanal
  - Karlie
  - keptn
  - Kuba
  - kubecon
  - k8sclusterreceiver
  - Langfuse
  - Langtrace
  - liatrio
  - lightstep
  - logz
  - Luca
  - maintainership
  - Makefiles
  - Marylia
  - observiq
  - opentelemetry
  - opentelemetrybot
  - otel
  - otel-localization-ptbr
  - otel-localization-zhcn
  - otep
  - otlp
  - passcodes
  - proto
  - Purvi
  - pytest
  - isovalent
  - labs
  - Liudmila
  - Nale
  - REXX
  - scaphandre
  - Sysplex
  - acramsay
  - adot
  - agentmanwg
  - alolita
  - amye
  - andré
  - aniszczyk
  - apac
  - anoshin
  - armin
  - beedgen
  - beemer
  - bertysentry
  - blanco
  - bogdan
  - boten
  - calendar-agent-mgmt
  - calendar-ebpf
  - caramanolis
  - cdevents
  - chrs
  - cicd
  - cijo
  - cncf
  - codeboten
  - codecentric
  - codecov
  - codeowners
  - comms
  - credly
  - danielgblanco
  - darren17082
  - davdai
  - denisivan
  - dennisme
  - dineshg
  - dmitrii
  - dmitryax
  - dpauls
  - dnsmichi
  - dpauls
  - drewby
  - drutu
  - dyla
  - dynatrace
  - easycla
  - ebpf
  - eiffel
  - emea
  - endsigs
  - faas
  - fong
  - frzifus
  - gbbr
  - genai
  - gitter
  - gitdm
  - henrikrexed
  - heptio
  - hongalex
  - horovits
  - instrgen
  - jackjia
  - jaglowski
  - javaagent
  - jemmic
  - juraci
  - kaiyan-sheng
  - kamphaus
  - kanzhelev
  - kelnage
  - keptn
  - krzko
  - kröhling
  - kubecon
  - kuisathaverat
  - lalitb
  - lambdanis
  - lexis
  - liatrio
  - lightstep
  - logz
  - lucavallin
  - lukas
  - lycheeverse
  - magnusbaeck
  - maintainership
  - mancuso
  - marceloamaral
  - martinkuba
  - mateuszrzeszutek
  - mayur
  - mayurkale
  - Metry
  - mdelfabro
  - mhausenblas
  - mirabella
  - mjwolf
  - mkorbi
  - molkova
  - msomasu
  - MSYS
  - PATHCONV
  - mtwo
  - mwear
  - npmjs
  - najaryan
  - nakamura
  - neumann
  - neumüller
  - nexis
  - nirga
  - nikimanoledaki
  - novotny
  - observiq
  - Olly
  - opamp
  - OpenLIT
  - opentelemetry
  - opentelemetrybot
  - ossf
  - otel
  - otel-agentmanwg
  - otel-comms
  - otel-ebpf
  - otelbot
  - otep
  - otlp
  - OTAP
  - OTTL
  - outreachy
  - Packagist
  - PECL
  - Prometheus
  - paixão
  - pająk
  - passcodes
  - poncelow
  - proto
  - protos
  - pytest
  - Quesma
  - raesene
  - reiley
  - roadmaps
  - rolldice
  - ruech
  - runtimes
  - rynn
  - rossf7
  - salnikov
  - sallyom
  - Santosh
  - sarif
  - scavarda
  - schäfer
  - semconv
  - sergey
  - severin
  - sguyon
  - sharma
  - shkuro
  - sigelman
  - signup
  - sig-localization-ptbr
  - sig-localization-zhcn
  - skyscanner
  - sloughter
  - snyk
  - splk
  - stalnaker
  - subdir
  - subproject
  - subprojects
  - subrepository
  - sudivate
  - suereth
  - supermajority
  - Thiru
  - Traceloop
  - tarnovski
  - tekton
  - thisthat
  - tiebreaking
  - tigran
  - timebox
  - timeboxing
  - timeslot
  - trask
  - trendable
  - triager
  - triagers
  - teamcity
  - uninstrumented
  - Vasconcellos
  - Vitor
  - vtex
  - yahn
