name: Move inactive members to Emeritus

on:
  workflow_dispatch:
  schedule:
    # At 05:00, on the 1st of every month
    - cron: '0 5 1 * *'

permissions:
  contents: read

jobs:
  move-to-emeritus:
    name: Move inactive members to emeritus
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.12'

      - uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: check-token
        with:
          app-id: ${{ vars.OTELBOT_APP_ID }}
          private-key: ${{ secrets.OTELBOT_PRIVATE_KEY }}
          owner: open-telemetry

      - name: Check activity and build report
        run: python -u scripts/move-to-emeritus.py --output /tmp/inactive-report.json --repo opentelemetry-js opentelemetry-js-contrib opentelemetry-java opentelemetry-java-contrib # Only checking a few repos for now since we want to verify the script works as expected before running it on all repos
        env:
          GITHUB_TOKEN: ${{ steps.check-token.outputs.token }}

      - uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: pr-token
        with:
          app-id: ${{ vars.OTELBOT_APP_ID }}
          private-key: ${{ secrets.OTELBOT_PRIVATE_KEY }}
          owner: open-telemetry

      - name: Create PRs from report
        run: python -u scripts/move-to-emeritus.py --input /tmp/inactive-report.json --create-prs
        env:
          GITHUB_TOKEN: ${{ steps.pr-token.outputs.token }}
