name: Reusable - Markdown link check

on:
  workflow_call:

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install markdown-link-check
        # fix version to 3.10.3 as 3.11.0 appears to ignore --config, so we can't specify our own
        # configuration file
        run: npm install -g markdown-link-check@3.10.3

      - name: Run markdown-link-check
        run: |
          find . -type f \
                 -name '*.md' \
                 -not -path './elections/2019/governance-committee-election.md' \
                 -not -path './elections/2020/governance-committee-election.md' \
                 -not -path './elections/*/governance-committee-candidates.md' \
               | xargs .github/scripts/markdown-link-check-with-retry.sh
