name: Spell checking

on:
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  spelling-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: streetsidesoftware/cspell-action@de2a73e963e7443969755b648a1008f77033c5b2 # v8.4.0
        with:
          config: .cspell.yaml
