name: Spell checking

on:
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  spelling-check:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: streetsidesoftware/cspell-action@6f3c77c1406bc930f944ba97e9801a22e42caf58 # v9.1.0
        with:
          config: .cspell.yaml
