name: SIG Table checking

on:
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  table-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: verify generated Markdown
        run: make check-generate
  validate-sigs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: validate workstreams.yml
        run: make validate-sigs
