name: Table of contents checking

on:
  pull_request:
  merge_group:

jobs:
  toc-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: check TOC in assets.md
        run: make markdown-toc-check
